angular.module('app').constant('I18N.MESSAGES', {
	
	'page.main.title' : 'IsoBrou',
	
	'msg.error.token.login.null' : 'Chave de Login Nula!',
	'msg.error.invalid.token' : 'Token Informado Inválido',
	
	/*FILE*/
	'lbl.general.displayName' : 'Nome de exibição',
	'lbl.general.chooseFile' : 'Selecione o arquivo',
	'lbl.general.search' : 'procurar',
	'lbl.general.upload' : 'Upload',
	'lbl.general.download' : 'Download',
	'lbl.general.filesList' : 'Lista de arquivos',
	'lbl.general.cancel' : 'Cancelar',
	'msg.error.upload.fail' : 'Upload com problemas',
	/*FIM FILE*/
		
		
		/* CADASTRO DE ESTABELECIMENTO*/
		'page.register.stored.title' : 'Cadastro de Estabelecimento',
		'lbl.data.stored':'Dados do Estabelecimento',
		'lbl.social.reason': 'Razão Social',
		'lbl.name.fantasy':'Nome Fantasia',
		'lbl.state.registration':'Inscrição Estadual',
		'lbl.complementary.information':'Informações Complementares',
		'lbl.image.logo.stored':'Imagem Logo do Estabelecimento',
		'lbl.communication.data.stored':'Dados de Comunicação do Estabelecimento',
		'lbl.commercial.phone':'Telefone Comercial',
		'lbl.cell.phone':'Celular',
		'lbl.fax':'Fax',
		'lbl.email':'E-mail',
		'lbl.address.stored':'Dados de Endereço do Estabelecimento',
		'lbl.cep':'CEP',
		'lbl.street':'Rua',
		'lbl.number':'Numero',
		'lbl.complement':'Complemento',
		'lbl.reference.point':'Ponto de Referencia',
		'lbl.neighborhood':'Bairro',
		'lbl.uf':'UF',
		'lbl.county':'Municipio',
		
		'placeholder.social.reason': 'Digite a Razão Social',
		'placeholder.name.fantasy':'Digite o Nome Fantasia',
		'placeholder.cnpj' : 'Digite o CNPJ',
		'placeholder.state.registration':'Digite sua Inscrição Estadual',
		'placeholder.complementary.information':'Digite suas Informações Complementares',
		'placeholder.commercial.phone':'Digit seu Telefone Comercial',
		'placeholder.cell.phone':'Digite seu Celular',
		'placeholder.fax':'Digite seu Fax',
		'placeholder.cep':'Digite seu CEP',
		'placeholder.street':'Digite o nome da sua Rua',
		'placeholder.number':'Digite seu Numero',
		'placeholder.complement':'Digite o Complemento',
		'placeholder.reference.point':'Digite o Ponto de Referencia',
		'placeholder.neighborhood':'Digite seu Bairro',
		'placeholder.uf':'Digite o UF',
		'placeholder.county':'Digite o Municipio',
		
		'btn.upload.image' : 'Upload Imagem',
		'lbl.password' : 'Senha',
		'lbl.cnpj' : 'CNPJ',
		'msg.save.success' : 'Cadastro Realizado com Sucesso!',
		'msg.save.error' : 'Cadastro Não Realizado!',
});