angular.module('app').constant('I18N.MESSAGES', {
	'msg.error.genneric' : 'Erro Genérico', 
	'msg.error.required.field' : '{0}: Campo Obrigatório',
	'msg.error.requireds.field' : 'Campos Obrigatórios Não Preenchidos',
	'msg.error.required.list' : 'Deve ser informado algum registro à lista: {0}',
	'msg.error.expeted.http.request' : 'Esperado um Http Request',
	'msg.error.bad.credentials' : 'Nome de Usuário / Senha Inválidos',
	'msg.error.wrong.password' : 'Senha Inválida',
	'msg.error.user.disabled' : 'Usuário Desabilitado',
	'msg.error.config.wrong.ambient' : 'Ambiente configurado de forma errada',
	'msg.error.expired.account"' : 'Conta Expirada',
	'msg.error.locked.account' : 'Conta Bloqueada',
	'msg.error.inative.account' : 'Conta Inativa',
	'msg.error.path.null' : 'Path Não Informado',
	'msg.error.application.null' : 'Aplicação Não Informada',
	'msg.error.unauthorized.path' : 'Sem Permissão de Acesso',
	'msg.error.password.encoder' : 'Erro ao Inicializar o Encoder',
	'msg.error.unauthorized.access' : 'Acesso não Autorizado',
	'msg.error.application.not.found' : 'Aplicação Não Encontrada',
	'msg.error.service.not.process' : 'Método chamado não responde',
	'msg.error.json' : 'Mapeamento Json com Problemas',
	'msg.error.filter' : 'Falhas no processamento da pesquisa',
	'msg.error.enum.not.found' : 'Classe Enum Informada não encontrada: {0}',
	'msg.error.enum.not.instantiation' : 'Classe Enum Informada não instanciada: {0}',
	'msg.error.list.null' : 'É necessário informar ao menos um item na lista: {0}',
	'msg.error.id.not.found' : 'Chave {0} informada para o Registro {1} não encontrada',
	'msg.error.application.required' : 'É necessário marcar ao menos uma Aplicação!',
	'msg.error.connect.ciello.init.payment' : 'Erro ao se conectar com o servidor da Ciello para iniciar uma transação: {0}',
	'msg.error.status.operation.ciello.invalid': 'Status de transação retornado inválido',
	'msg.error.status.capture.ciello.invalid' : 'Status de captura de transação retornado inválido',
	'msg.error.sql' : 'Erro no Acesso ao Banco de Dados: {0}', 
	'msg.error.connect.ciello.cancel.payment' : 'Erro ao se conectar com o servidor da Ciello para Cancelar uma transação: {0}',
	'msg.error.invalid.field' : 'Campo Inválido: {0}',
	'msg.error.length.field' : 'O Campo {0} Deve ter menos que {1} caracteres',
	'msg.error.invalid.format.field' : 'Formato de Campo Inválido: {0}',
	'msg.error.dt.before.today' : 'A data deve ser maior que a data atual: {0}',
	'msg.error.invalid.amount.sale' : 'Valor da Compra não pode ser inferior a R$ 5,00',
    'msg.error.payment' : 'Houveram falhas no Processo de Efetivação da Compra junto ao Cartão. Favor tentar novamente',
    'msg.error.invalid.token' : 'Token Informado Inválido',
    'msg.error.token.login.null' : 'Token não informado',	
	'msg.error.pagmto.denied' : 'Pagamento Não Autorizado pela Instituição Financeira',
	'msg.error.pagmto.voided' : 'Pagamento Cancelado',
	'msg.error.pagmto.refunded' : 'Pagamento Cancelado/Estornado',
	'msg.error.pagmto.pending' : 'Pagamento Não Processado pela Instituição Financeira',
	'msg.error.cep.not.found' : 'Nenhum endereço encontrado para este cep',
	'msg.error.list.not.found' : 'Nenhum elemento encontrado para a pesquisa realizada!',
	'msg.error.read.tmp.file' : 'Erro ao ler arquivo temporário',
	'msg.error.save.tmp.file' : 'Erro ao salvar arquivo temporário',
	'msg.error.connection' : 'Conexão não estabelecida com o servidor: {0}',
	'msg.error.file.empty' : 'Arquivo Vazio: {0}',
	'msg.error.crud.file'  : 'Operação sobre o arquivo {0} não realizada!',
	'msg.error.read.file' : 'Erro ao ler arquivo',
	'msg.error.init.file' : 'Erro ao Inicializar Arquivo',
	'msg.error.same.user' : 'Já existe(m) usuário(s) cadastrado(s) com este mesmo cpf / email informado',
	'msg.error.fields.list' : 'Problemas com os seguintes campos:',
	'msg.error.nor.fields' : 'Ao menos um dos campos é obrigatório: {N}',
	'msg.error.location.search.not.found' : 'Localização de Endereço para pesquisa não informado',
	'msg.error.product.not.sufficient' : 'Existem apenas {0} itens em estoque para o produto {1}',
	'msg.error.validations.pre.payment' : 'Ocorreram problemas de validação do pedido antes de efetuar o pagamento',
	'msg.error.product.price' : 'Valor informado do produto menor que o cadastrado',
	'msg.error.delete.file' : 'Erro ao deletar o arquivo {0}!',
	'msg.error.register.operation' : 'Erro ao {0} registro: {1}',
	
	'msg.confirm.cancel.operation' : 'Deseja Cancelar a Operação ?',
	'msg.confirm.payment' : 'Confirma o pagamento de R$ {0} ?',

	'msg.user.logged': 'O usuário {0} encontra-se logado. Deseja entrar com uma conta diferente?',
	'msg.save.success': 'Cadastro Realizado com Sucesso!',
	'msg.update.success': 'Alteração Realizada com Sucesso!',
	'msg.delete.success': 'Exclusão Realizada com Sucesso!',
	'msg.payment.success' : 'Pagamento Realizado com Sucesso.',
	
	'lbl.general.noRecordsFound' : 'Nenhum Registro Retornado',

	'lbl.id' : 'ID',
	'lbl.email' : 'Email',
	'lbl.cpf' : 'CPF',
	'lbl.password' : 'Senha',
	'lbl.record' : 'Registro',
	'lbl.entity.name' : 'Nome da Entidade',
	'lbl.entity.description' : 'Descrição da Entidade',
	'lbl.field.type' : 'Tipo do Campo',
	'lbl.field.name' : 'Nome do Campo',
	'lbl.single.atributte' : 'Atributos Simples',
	'lbl.relation.type' : 'Tipo da Relação',
	'lbl.relation.children' : 'Filho da Relação',
	'lbl.name' : 'Nome',
	'lbl.description' : 'Descrição',
	'lbl.entity.fields' : 'Campos da Entidade',
	'lbl.save' : 'Salvar',
	'lbl.update' : 'Alteração',
	'lbl.filter' : 'Filtro',
	'lbl.device.undefined' : 'Indefinido',
	'lbl.device.mobile' : 'Celular',
	'lbl.device.tablet' : 'Tablet',
	'lbl.device.desktop' : 'Desktop',
	'lbl.general.recordsNumber' : 'Registros',
	'lbl.general.select' : 'Selecione',
	'lbl.text' : 'Texto',
	'lbl.date' : 'Data',
	'lbl.numeric' : 'Número',
	'lbl.monetary' : 'Moeda',
	'lbl.cnpj' : 'CNPJ',
	'lbl.pk' : 'PK',
	'lbl.user.create' : 'Usuário de Criação',
	'lbl.relationship' : 'Relacionamento entre Entidades',
	'lbl.entity.ref' : 'Entidade de Referência',
	'lbl.application': 'Aplicação',
	'lbl.one.to.one' : 'Um para Um',
	'lbl.one.to.many' : 'Um para Muitos',
	'lbl.many.to.one' : 'Muitos para Um',
	'lbl.many.to.many' : 'Muitos para Muitos',
	'lbl.credit' : 'Crédito',
	'lbl.debit' : 'Débito',
	'lbl.card.visa' : 'Visa',
	'lbl.card.master' : 'Master Card',
	'lbl.card.amex' : 'American Express',
	'lbl.card.elo' : 'Elo',
	'lbl.card.dinners' : 'Diners Club',
	'lbl.application.payment' : 'Informações de Pagamento para a Aplicação',
	'lbl.payment.not.finished' : 'Falha ao processar o pagamento',
	'lbl.payment.authorized' : 'Meio de pagamento apto a ser capturado ou pago (Boleto)',
	'lbl.payment.confirmed.paymed' : 'Pagamento confirmado e finalizado',
	'lbl.payment.denied' : 'Negado',
	'lbl.payment.voided' : 'Pagamento cancelado',
	'lbl.payment.refunded' : 'Pagamento Cancelado/Estornado',
	'lbl.payment.pending' : 'Esperando retorno da instituição financeira',
	'lbl.payment.aborted' : 'Pagamento cancelado por falha no processamento',
	'lbl.payment.scheduled' : 'Recorrência agendada',
	'lbl.payment.id' : 'Chave da Transação',
	'lbl.payment.url.return' : 'URL de Retorno da Aplicação',
	'lbl.payment.date.expiration' : 'Data de Expiração',
	'lbl.payment.sale' : 'Registro da Venda',
	'lbl.payment.brand' : 'Bandeira do Cartão',
	'lbl.payment.card.number' : 'Número do Cartão',
	'lbl.payment.customer.name' : 'Nome do Cliente',
	'lbl.payment.card.name' : 'Nome Impresso no Cartão',
	'lbl.payment.security.code' : 'Código de Segurança do Cartão',
	'lbl.payment.amount' : 'Valor da Compra',
	'lbl.payment' : 'Pagamento',
	'lbl.payment.type' : 'Tipo de Pagamento',
	'lbl.payment.merchant.order.id' : 'Ordem de Pagamento',
	'lbl.product.type' : 'Tipo de Produto',
	'lbl.product.name' : 'Nome do Produto',
	'lbl.dt.expiration' : 'Data de Validade',
	'lbl.value' : 'Valor',
	'lbl.amount' : 'Quantidade',
	'lbl.store' : 'Estabelecimento',
	'lbl.queue' : 'Fila',
	'lbl.url' : 'URL',
	'lbl.mail.to' : 'Endereço Destinatário do Email',
	'lbl.mail.name' : 'Nome do Destinatário do Email',
	'lbl.mail.template' : 'Template do Email',
	'lbl.mail.attachment' : 'Anexo do Email',
	'lbl.rg' : 'RG',
	'lbl.photo' : 'Imagem',
	'lbl.residencial.phone':'Telefone Residencial',
	'lbl.address' : 'Endereço',
	'lbl.user' : 'Usuário',
	'lbl.username' : 'Login',
	'lbl.device' : 'Equipamento',
	'lbl.birthday' : 'Data de Nascimento',
	'lbl.location' : 'Localização',
	'lbl.latitude' : 'Latitude',
	'lbl.longitude' : 'Longitude',
	'lbl.flg.without.address' : 'Com Ou Sem Endereço',
	'lbl.city' : 'Cidade',
	'lbl.initials' : 'Sigla',
	'lbl.order' : 'Pedidos',	
	'lbl.customer' : 'Cliente',
	'lbl.dt.order' : 'Data do Pedido',
	'lbl.instance.flow' : 'Instância de WorkFlow',
	'lbl.sponsor' : 'Nome do Responsável',
	'lbl.id.order' : 'Id do Pedido',
	'lbl.product' : 'Produto',
	
	/*ENUMS*/
	'lbl.type.person.physical' : 'Pessoa Físcia',
	'lbl.type.person.legal' : 'Pessoa Jurídica',	
	
	'lbl.menu.header' : 'Menu',
	'lbl.menu.item.entities.crud': 'Cadastro de Entidades',
	'lbl.menu.item.entities' : 'Entidades',
	
	'lbl.menu.filter' : 'Filtro',
	'lbl.menu.new.item' : 'Novo Cadastro',
	'lbl.menu.item.2' : 'Teste 2',
	'lbl.menu.item.2.1' : 'Teste 2.1',
	'lbl.menu.item.3' : 'Teste 3',
	'lbl.menu.item.3.1' : 'Teste 3.1',
	'lbl.menu.item.3.1.1' : 'Teste 3.1.1',
	'lbl.menu.item.3.1.1.1' : 'Teste 3.1.1.1',
	'lbl.menu.item.3.1.2' : 'Teste 3.1.2',
	'lbl.menu.item.3.1.2.1' : 'Teste 3.1.2.1',
	'lbl.menu.item.3.2' : 'Teste 3.2',
	'lbl.menu.item.3.2.1' : 'Teste 3.2.1',
	'lbl.menu.item.3.3' : 'Teste 3.3',
	
	'lbl.footer.1' : 'GitHub',
	'lbl.footer.2' : 'About',
	'lbl.footer.3' : 'Suport',
	
	'page.login.title' : 'Login',
	'page.main.title' : 'Entidades',
	'page.entity.save.title' : 'Cadastro de Entidades',
	'page.entity.update.title' : 'Alteração de Entidades',
	'page.entity.filter.title' : 'Pesquisa de Entidades',
	'page.title.home' : 'Home',
	'page.field.modal.title' : 'Campo da Entidade',
	'page.payment.title' : 'Pagamento',
	'page.product.save.title' : 'Cadastro de Produtos',
	'page.customer.save.title' : 'Cadastro de Clientes',
	
	'list.entity.title' : 'Entidades Cadastradas',
	'list.entity.field.title' : 'Campos da Entidade',
	
	'btn.login' : 'Log In',
	'btn.logout' : 'Log Out',
	
	'btn.edit' : 'Editar',
	'btn.exclude' : 'Excluir',
	'btn.save' : 'Salvar',
	'btn.cancel' : 'Cancelar',
	'btn.filter' : 'Pesquisar',
	'btn.new.field' : 'Novo Campo',
	'btn.return' : 'Retornar',
	'btn.payment' : 'Pagar',
	
	'placeholder.email' : 'Digite seu Email',
	'placeholder.cpf' : 'Digite seu CPF',
	'placeholder.password' : 'Digite sua Senha',
	'placeholder.entity.name' : 'Digite o Nome da Entidade',
	'placeholder.entity.description' : 'Digite a Descrição da Entidade',
	'placeholder.field.description' : 'Digite a Descrição do Campo',
	'placeholder.field.name' : 'Digite o Nome do Campo',
	'placeholder.payment.card.name': 'Digite o Nome como está impresso no Cartão',
	
	/* CADASTRO DE ESTABELECIMENTO*/
	'page.register.stored.title' : 'Cadastro de Estabelecimento',
	'lbl.data.stored':'Dados do Estabelecimento',
	'lbl.social.reason': 'Razão Social',
	'lbl.name.fantasy':'Nome Fantasia',
	'lbl.state.registration':'Inscrição Estadual',
	'lbl.complementary.information':'Informações Complementares',
	'lbl.image.logo.stored':'Imagem Logo do Estabelecimento',
	'lbl.communication.data.stored':'Dados de Comunicação do Estabelecimento',
	'lbl.commercial.phone':'Telefone Comercial',
	'lbl.cell.phone':'Celular',
	'lbl.fax':'Fax',
	'lbl.email':'E-mail',
	'lbl.address.stored':'Dados de Endereço do Estabelecimento',
	'lbl.cep':'CEP',
	'lbl.street':'Rua',
	'lbl.number':'Numero',
	'lbl.complement':'Complemento',
	'lbl.reference.point':'Ponto de Referencia',
	'lbl.neighborhood':'Bairro',
	'lbl.uf':'UF',
	'lbl.country':'País',
	
	'placeholder.social.reason': 'Digite a Razão Social',
	'placeholder.name.fantasy':'Digite o Nome Fantasia',
	'placeholder.cnpj' : 'Digite o CNPJ',
	'placeholder.state.registration':'Digite sua Inscrição Estadual',
	'placeholder.complementary.information':'Digite suas Informações Complementares',
	'placeholder.commercial.phone':'Digit seu Telefone Comercial',
	'placeholder.cell.phone':'Digite seu Celular',
	'placeholder.fax':'Digite seu Fax',
	'placeholder.cep':'Digite seu CEP',
	'placeholder.street':'Digite o nome da sua Rua',
	'placeholder.number':'Digite seu Numero',
	'placeholder.complement':'Digite o Complemento',
	'placeholder.reference.point':'Digite o Ponto de Referencia',
	'placeholder.neighborhood':'Digite seu Bairro',
	'placeholder.uf':'Digite o UF',
	'placeholder.county':'Digite o Municipio',
	
	'btn.upload.image' : 'Upload Imagem',
	
		
});